obj-y += iommu.o
obj-$(CONFIG_ARM_SMMU) += smmu.o
obj-$(CONFIG_RCAR_IPMMU) += ipmmu-vmsa.o
obj-$(CONFIG_RCAR_IPMMU) += io-pgtable.o
obj-$(CONFIG_RCAR_IPMMU) += io-pgtable-arm.o
obj-$(CONFIG_RCAR_IPMMU) += ipmmu-vmsa-plat.o
