obj-y += pci.o
obj-y += pci-host-generic.o
obj-y += pci-host-common.o
obj-y += pci-access.o
obj-y += ecam.o
obj-$(CONFIG_PCIE_XILINX_NWL) += pci-host-zynqmp.o
obj-$(CONFIG_PCIE_RCAR_GEN3) += pci-host-rcar-gen3.o
